services:
  ffc-sfd-customer-receiver-payments:
    build:
      context: .
      target: production
    image: ffc-sfd-customer-receiver-payments
    container_name: ffc-sfd-customer-receiver-payments
    depends_on:
      - ffc-sfd-customer-receiver-payments-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfd-customer-receiver-payments-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}

  ffc-sfd-customer-receiver-payments-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc-sfd-customer-receiver-payments
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
