version: '3.8'
# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sfd-customer-receiver-payments:
    build:
      target: development
    image: ffc-sfd-customer-receiver-payments-development
    container_name: ffc-sfd-customer-receiver-payments-development
    ports:
      - "3013:3013"
      - "9013:9229"
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./scripts:/home/node/scripts
      - ./package.json:/home/node/package.json
