services:
  ffc-sfd-customer-receiver-payments:
    build:
      context: .
      target: production
    image: ffc-sfd-customer-receiver-payments
    container_name: ffc-sfd-customer-receiver-payments
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfd-customer-receiver-payments-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      MESSAGE_HOST: ${MESSAGE_HOST}
      MESSAGE_USER: ${MESSAGE_USER}
      MESSAGE_PASSWORD: ${MESSAGE_PASSWORD}
      PAYMENTS_SUBSCRIPTION_ADDRESS: ${PAYMENTS_SUBSCRIPTION_ADDRESS}-${DEV_SUFFIX}
      PAYMENTS_TOPIC_ADDRESS: ${PAYMENTS_TOPIC_ADDRESS}-${DEV_SUFFIX}
      COSMOS_ENDPOINT: ${COSMOS_ENDPOINT:-https://cosmos-db:8081}
      COSMOS_KEY: ${COSMOS_KEY}
      DEV_SUFFIX: ${DEV_SUFFIX}
