services:
  ffc-sfd-customer-receiver-payments:
    build:
      context: .
      target: production
    image: ffc-sfd-customer-receiver-payments
    container_name: ffc-sfd-customer-receiver-payments
    depends_on:
      - ffc-sfd-customer-receiver-payments-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfd-customer-receiver-payments-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
