- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: MESSAGE_HOST
  value: "SNDADPINFSB4401.servicebus.windows.net"
- key: PAYMENTS_TOPIC_ADDRESS
  value: "fcp-sfd-customer-payments"
- key: PAYMENTS_SUBSCRIPTION_ADDRESS
  value: "fcp-sfd-customer-receiver-payments"